ALTER TABLE stores ADD COLUMN leave_min_notice_days INTEGER NOT NULL DEFAULT 1;
ALTER TABLE stores ADD COLUMN leave_max_notice_days INTEGER NOT NULL DEFAULT 5;
ALTER TABLE stores ADD COLUMN leave_monthly_limit INTEGER NOT NULL DEFAULT 4;
ALTER TABLE stores ADD COLUMN leave_daily_limit INTEGER NOT NULL DEFAULT 1;
